spring.application.name=auth-service

server.port=9094

spring.datasource.url=jdbc:postgresql://localhost:5434/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


jwt.secret=change-this-secret-key-change-this-secret-key
jwt.expiration-ms=3600000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs