version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
    ports:
      - "9092:9092"   # REST API port
    networks:
      - microservices-net

volumes:
  orders-db-data:

networks:
  microservices-net:
    external: true
