
# REST API port
server.port=8080

# gRPC server port
grpc.server.port=9090


spring.datasource.url=jdbc:postgresql://postgres:5432/ordersdb
spring.datasource.username=yourusername
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.net.devh.boot.grpc.server=DEBUG
logging.level.org.springframework=INFO