version: '3.8'

services:

  # ======================
  # AUTH DATABASE
  # ======================
  auth-postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - microservices-net
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  # ======================
  # AUTH SERVICE
  # ======================
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - auth-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: change-this-secret-key-change-this-secret-key
      JWT_EXPIRATION_MS: 3600000
    ports:
      - "9094:9094"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    external: true

volumes:
  auth-db-data:
