spring.datasource.url=jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

grpc.client.inventory-service.address=static://host.docker.internal:9090
grpc.client.inventory-service.negotiation-type=plaintext

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#grpc.server.port=9091

server.port=9092

grpc.metrics.enabled=false