# ======================
# SERVER
# ======================
server.port=8080
grpc.server.port=9090

# ======================
# DATABASE
# ======================
spring.datasource.url=jdbc:postgresql://postgres:5432/inventorydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA (IMPORTANT FIX)
# ======================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# SQL INIT
# ======================
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# ======================
# LOGGING
# ======================
logging.level.root=INFO
logging.level.net.devh.boot.grpc.server=DEBUG
logging.level.org.springframework=INFO

# ======================
# ACTUATOR
# ======================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ======================
# KAFKA CONSUMER
# ======================
spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.auto-offset-reset=earliest
app.kafka.topic.inventory-events=inventory-events

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.inventoryservice.infrastructure.kafka.dto.InventorySyncEvent



