version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    external: true

volumes:
  pgdata:
